import { z } from "zod";
import { SHOPIFY_ROUTE_TOPICS } from "../domain/shopify.constants.js";

export const shopifyRouteTopicSchema = z.enum([
  SHOPIFY_ROUTE_TOPICS.ORDERS_CREATE,
  SHOPIFY_ROUTE_TOPICS.ORDERS_FULFILLED,
  SHOPIFY_ROUTE_TOPICS.FULFILLMENTS_CREATE,
  SHOPIFY_ROUTE_TOPICS.ORDERS_CANCELLED,
  SHOPIFY_ROUTE_TOPICS.CHECKOUTS_UPDATE,
  SHOPIFY_ROUTE_TOPICS.ABANDONED_CHECKOUTS
]);
